= AsciiSlide
:lang: en

Create presentation slides with AsciiDoc.

== Example

- PDF: link:https://snwnde.github.io/AsciiSlide/example/main.pdf[example.pdf]
- HTML: link:https://snwnde.github.io/AsciiSlide/example/main.html[example.html]

== Usage

=== CI (recommended)

Use the image `ghcr.io/snwnde/asciislide` in your CI pipeline.

Set `ASCIISLIDE_SRC_DIR` to the directory containing the AsciiDoc source files, and `ASCIISLIDE_BUILD_DIR` to the output directory for the generated slides.

Then run `make` inside the container.


=== Local (with Docker)

Use Docker locally if you want the same build environment as CI.

Your project typically has the following structure:
----
.
|-- Makefile
|-- build
`-- src
    |-- images
    `-- main.adoc
----

Your `Makefile` can look like this:

----
.PHONY: all clean

all:
	@docker run --rm \
		-v ./build:/asciislide/build \
		-v ./src:/asciislide/src \
		ghcr.io/snwnde/asciislide make

clean:
	@rm -rf build/*
----

Then run `make` to generate the slides in `build`.

=== Local (without Docker)

If you prefer to build locally without Docker, install link:https://github.com/ggrossetie/asciidoctor-web-pdf[asciidoctor-web-pdf] and make sure it is available in your `PATH`.

Clone this repository, change into the `asciislide` directory, and place your AsciiDoc source files in `src`. The layout should look like this:

----
.
|-- Makefile
|-- assets
|-- build
|-- converter.js
`-- src
    |-- images
    `-- main.adoc
----

Then run `make` to generate the slides in `build`.

== Inspirations

- link:https://matklad.github.io/2019/05/19/consider-using-asciidoctor-for-your-next-presentation.html[Consider Using Asciidoctor for Your Next Presentation]

- link:https://github.com/nikolaialex/asciidoc-slides/[Asciidoc-Slides]
